[package]
name = "casperlabs-engine-storage"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]

[dependencies]
failure = "0.1.5"
lmdb = "0.8.0"
wasmi = "0.4.2"
contract-ffi = { path = "../contract-ffi", features = ["std", "gens"], package = "casperlabs-contract-ffi" }
engine-shared = { path = "../engine-shared", package = "casperlabs-engine-shared" }
parking_lot = "0.7.1"

[dev-dependencies]
lazy_static = "1.3.0"
proptest = "0.9.2"
tempfile = "3"
