apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  version: 1
  editable: true
  # Set the X axis resolution on time series to the Prometheus
  # scrape interval so we don't lose observations if possible.
  jsonData:
    timeInterval: 5s