[package]
name = "test_args_multi"
version = "0.1.0"
authors = ["Joe Sacher <joe@casperlabs.io>"]
edition = "2018"

[lib]
name = "test_args_multi"
crate-type = ["cdylib"]

[features]
default = []
std = ["cl_std/std" ]

[dependencies]
cl_std = { path = "../../../../execution-engine/contract-ffi", package = "casperlabs-contract-ffi" }
