[package]
name = "create-test-node-01"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[dependencies]
create-test-node-shared = { path = "../create-test-node-shared" }
