[package]
name = "list-known-urefs-define"
version = "0.1.0"
authors = ["Mateusz Górski <mateusz@casperlabs.io>"]

[lib]
name = "listknownurefsdefine"
crate-type = ["cdylib"]

[dependencies]
common = { package = "casperlabs-contract-ffi", path = "../../../../execution-engine/contract-ffi" }

